<Project>
  <PropertyGroup>
    <Platforms>x64;x86</Platforms>
    <Platform Condition="'$(Platform)' == '' Or '$(Platform)' == 'AnyCPU' Or '$(Platform)' == 'Any CPU'">x64</Platform>
    <PlatformTarget Condition="'$(Platform)' == 'x64'">x64</PlatformTarget>
    <PlatformTarget Condition="'$(Platform)' == 'x86'">x86</PlatformTarget>
  </PropertyGroup>
</Project>