<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\NetLoom.Application\NetLoom.Application.csproj" />
    <ProjectReference Include="..\..\src\NetLoom.Domain\NetLoom.Domain.csproj" />
    <ProjectReference Include="..\..\src\NetLoom.Protocols.Snmp\NetLoom.Protocols.Snmp.csproj" />
    <ProjectReference Include="..\..\src\NetLoom.Topology\NetLoom.Topology.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>