<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NetLoom.Contracts\NetLoom.Contracts.csproj" />
    <ProjectReference Include="..\NetLoom.Application\NetLoom.Application.csproj" />
    <ProjectReference Include="..\NetLoom.Domain\NetLoom.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>