<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>NetLoom.HostLogging</RootNamespace>
    <AssemblyName>NetLoom.HostLogging</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="6.2.0" />
  </ItemGroup>
</Project>
